### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by sheenli** [jingwood/js-graphics-math#1]
![image](https://user-images.githubusercontent.com/13329486/71825672-49a6ee00-30d7-11ea-8927-0dfdd9a3eb66.png)

**Comment by jingwood** [comment]
The script `npm run build` has been fixed now.
You can run `npm pack` to make a package after building. I have been publish a npm package at 
https://www.npmjs.com/package/@jingwood/graphics-math

Hope this library helps you!
